#include "CombatBehaviorNodesMovement.h"

namespace RE
{
	DEFINE_CombatBehaviorTree_XXX__createnew(46753, CombatBehaviorTreeCreateContextNode_CombatBehaviorContextCloseMovement_);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorFallback, 46762);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorBackoff, 46759);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorSurround, 46765);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorReposition, 46764);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorAdvance, 46758);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorFallbackToRanged, 46763);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorCircle, 46760);
	DEFINE_CombatBehaviorTreeNodeObject_createnew(CombatBehaviorCircleDistant, 46761);

}